
package cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://Controle/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Echo {


    /**
     * 
     * @param titulo
     * @return
     *     returns java.util.List<cliente.TimeVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://Controle/", className = "cliente.Echo_Type")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://Controle/", className = "cliente.EchoResponse")
    @Action(input = "http://Controle/Echo/echoRequest", output = "http://Controle/Echo/echoResponse")
    public List<TimeVO> echo(
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo);

}
